// 4cfa13fc88b6ed99d68e9f02a9b9f99f2847abbd
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "2.8.1"
#define GIT_HASH "4cfa13fc88b6ed99d68e9f02a9b9f99f2847abbd"
#define GIT_TIME "2016-02-16 15:46:35 +0300"
